#!/usr/bin/env python3
"""Generate immutable dBase Unicode case tables for libd64_qt5.dll."""
from pathlib import Path
import unicodedata

def upper_string(value: str) -> str:
    return "".join(c if c == "ß" else c.upper() for c in value)

def lower_string(value: str) -> str:
    return value.lower()

def mapping_rows(mapper):
    rows=[]
    for cp in range(128,0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        c=chr(cp)
        mapped=mapper(c)
        if mapped == c:
            continue
        source=c.encode("utf-8")
        result=mapped.encode("utf-8")
        rows.append((int.from_bytes(source,"little"),result))
    return tuple(rows)

def packed_bytes(rows):
    out=bytearray()
    for key,value in rows:
        out += int(key).to_bytes(4,"little")
        out.append(len(value))
        out += value
    out += b"\0\0\0\0"
    return bytes(out)

def emit_array(name,payload):
    lines=[f"static const std::uint8_t {name}[] = {{"]
    for start in range(0,len(payload),20):
        chunk=payload[start:start+20]
        lines.append("    "+", ".join(f"0x{b:02X}" for b in chunk)+",")
    lines.append("};")
    return "\n".join(lines)

def render():
    upper=packed_bytes(mapping_rows(upper_string))
    lower=packed_bytes(mapping_rows(lower_string))
    return "\n".join([
        "// ---------------------------------------------------------------------------",
        "// AUTO-GENERATED by generate_dbase_case_tables.py -- do not hand edit.",
        f"// Python Unicode database: {unicodedata.unidata_version}",
        "// Stage 208/209: immutable dBase case tables live in libd64_qt5.dll.",
        "// ---------------------------------------------------------------------------",
        "#pragma once","",
        emit_array("__dbase_upper_table",upper),"",
        emit_array("__dbase_lower_table",lower),"",
        f"static const std::uint32_t __dbase_upper_table_size = {len(upper)}u;",
        f"static const std::uint32_t __dbase_lower_table_size = {len(lower)}u;",""
    ])

def main():
    destination=Path(__file__).with_name("d64_dbase_case_tables.inc")
    destination.write_text(render(),encoding="utf-8",newline="\n")
    print(destination)

if __name__ == "__main__":
    main()
