#!/usr/bin/env python3
"""Stage 213: generate the runtime ordinal-map SHA-256 include from the DEF.

The ordinal-map version is intentionally explicit/manual. The hash changes even
when someone forgets to bump that version, so the loader still detects a map
mismatch. Existing exports use explicit ordinals in d64qt5_bridge.def.
"""
from __future__ import annotations
from pathlib import Path
import hashlib
import re

ROOT = Path(__file__).resolve().parent
DEF = ROOT / "d64qt5_bridge.def"
OUT = ROOT / "d64_runtime_abi.inc"
ABI_MAJOR = 1
ABI_MINOR = 2
ORDINAL_MAP_VERSION = 2
MIN_LOADER_VERSION = 0x00010000
RUNTIME_NAME = "libd64_qt5.dll"


def read_exports():
    rows = []
    seen_ordinals = set()
    for raw in DEF.read_text(encoding="utf-8").splitlines():
        line = raw.split(";", 1)[0].strip()
        if not line or line.upper() == "EXPORTS" or line.upper().startswith("LIBRARY"):
            continue
        match = re.match(r"^([^\s]+)\s+@(\d+)(?:\s|$)", line)
        if not match:
            raise SystemExit(f"Export ohne explizites Ordinal: {line}")
        name, ordinal_text = match.groups()
        ordinal = int(ordinal_text)
        if not 1 <= ordinal <= 0xFFFF:
            raise SystemExit(f"Ungültiges Ordinal @{ordinal}: {name}")
        if ordinal in seen_ordinals:
            raise SystemExit(f"Doppeltes Ordinal @{ordinal}")
        seen_ordinals.add(ordinal)
        rows.append((ordinal, name))
    rows.sort(key=lambda item: (item[0], item[1].casefold(), item[1]))
    return rows


def main() -> int:
    rows = read_exports()
    canonical = "".join(f"{ordinal}:{name}\n" for ordinal, name in rows).encode("ascii")
    digest = hashlib.sha256(canonical).digest()
    byte_rows = []
    for offset in range(0, 32, 8):
        suffix = "," if offset + 8 < 32 else ""
        byte_rows.append(
            "    " + ", ".join(f"0x{value:02X}" for value in digest[offset:offset+8]) + suffix
        )
    OUT.write_text(
        "// Auto-generated by generate_runtime_abi.py.\n"
        "#pragma once\n#include <cstdint>\n\n"
        f"static constexpr std::uint16_t D64_RUNTIME_ABI_MAJOR = {ABI_MAJOR}u;\n"
        f"static constexpr std::uint16_t D64_RUNTIME_ABI_MINOR = {ABI_MINOR}u;\n"
        f"static constexpr std::uint32_t D64_RUNTIME_ORDINAL_MAP_VERSION = {ORDINAL_MAP_VERSION}u;\n"
        f"static constexpr std::uint32_t D64_RUNTIME_MIN_LOADER_VERSION = 0x{MIN_LOADER_VERSION:08X}u;\n"
        f"static constexpr const char D64_RUNTIME_NAME[] = \"{RUNTIME_NAME}\";\n"
        "static constexpr std::uint8_t D64_RUNTIME_ORDINAL_MAP_HASH[32] = {\n"
        + "\n".join(byte_rows)
        + "\n};\n",
        encoding="utf-8",
    )
    print(f"D64 runtime exports: {len(rows)}")
    print(f"Ordinal map SHA-256: {digest.hex()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
