# Project: Commodore C= 64 Dissassembler
# Generated by HelpNDoc - https://www.helpndoc.com

help_topics = {
    "Vorlage1": 20,
    "VorlagePage1": 29,
    "Befehle6510": 1,
    "LDX": 2,
    "SEI": 3,
    "STX": 4,
    "RAMRESET": 0,
    "ZEROPAGE": 6,
    "ZEROPAGEREL": 5,
    "Anhang": 23,
    "MIT-Lizenz-Deutsch": 24,
    "MIT-Lizenz-Englisch": 25,
    "MIT-Lizenz-Franzosisch": 26,
    "MIT-Lizenz-Spanisch": 27,
    "MIT-Lizenz-Polinsch": 28,
    "MIT-Lizenz-Russisch": 30
}
